# Cloudflare Workers configuration
name = "slack-reaction-generator"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

# 静的アセットの設定
assets = { directory = "./dist" }

# ビルド設定
[build]
command = "npm run build"

# 開発環境設定
[dev]
port = 8787
local_protocol = "http"